# Generated by Django 2.0.2 on 2018-04-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
            ],
        ),
    ]
